// This file will be auto-generated by `npx supabase gen types typescript`
// For now, we use a minimal placeholder so the Supabase client is typed.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          role: string | null;
          display_name: string;
          avatar_url: string | null;
          bio: string | null;
          genre_specialties: string[] | null;
          writers_choice_count: number;
          audience_favorite_count: number;
          created_at: string;
        };
        Insert: {
          id: string;
          role?: string | null;
          display_name: string;
          avatar_url?: string | null;
          bio?: string | null;
          genre_specialties?: string[] | null;
          writers_choice_count?: number;
          audience_favorite_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          role?: string | null;
          display_name?: string;
          avatar_url?: string | null;
          bio?: string | null;
          genre_specialties?: string[] | null;
          writers_choice_count?: number;
          audience_favorite_count?: number;
          created_at?: string;
        };
      };
      scripts: {
        Row: {
          id: string;
          writer_id: string;
          title: string;
          genre: string;
          logline: string;
          file_url: string;
          parsed_json: Json | null;
          status: string;
          submission_deadline: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          writer_id: string;
          title: string;
          genre: string;
          logline: string;
          file_url: string;
          parsed_json?: Json | null;
          status?: string;
          submission_deadline: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          writer_id?: string;
          title?: string;
          genre?: string;
          logline?: string;
          file_url?: string;
          parsed_json?: Json | null;
          status?: string;
          submission_deadline?: string;
          created_at?: string;
        };
      };
      characters: {
        Row: {
          id: string;
          script_id: string;
          name: string;
          description: string | null;
          line_count: number;
        };
        Insert: {
          id?: string;
          script_id: string;
          name: string;
          description?: string | null;
          line_count?: number;
        };
        Update: {
          id?: string;
          script_id?: string;
          name?: string;
          description?: string | null;
          line_count?: number;
        };
      };
      submissions: {
        Row: {
          id: string;
          actor_id: string;
          character_id: string;
          script_id: string;
          video_url: string;
          take_number: number;
          is_writers_choice: boolean;
          is_audience_favorite: boolean;
          vote_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id: string;
          character_id: string;
          script_id: string;
          video_url: string;
          take_number?: number;
          is_writers_choice?: boolean;
          is_audience_favorite?: boolean;
          vote_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          actor_id?: string;
          character_id?: string;
          script_id?: string;
          video_url?: string;
          take_number?: number;
          is_writers_choice?: boolean;
          is_audience_favorite?: boolean;
          vote_count?: number;
          created_at?: string;
        };
      };
      assembled_reads: {
        Row: {
          id: string;
          script_id: string;
          video_url: string | null;
          youtube_url: string | null;
          view_count: number;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          script_id: string;
          video_url?: string | null;
          youtube_url?: string | null;
          view_count?: number;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          script_id?: string;
          video_url?: string | null;
          youtube_url?: string | null;
          view_count?: number;
          status?: string;
          created_at?: string;
        };
      };
      votes: {
        Row: {
          id: string;
          user_id: string;
          submission_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          submission_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          submission_id?: string;
          created_at?: string;
        };
      };
      comments: {
        Row: {
          id: string;
          user_id: string;
          assembled_read_id: string;
          scene_index: number | null;
          body: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          assembled_read_id: string;
          scene_index?: number | null;
          body: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          assembled_read_id?: string;
          scene_index?: number | null;
          body?: string;
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          payload: Json;
          read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          payload?: Json;
          read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          payload?: Json;
          read?: boolean;
          created_at?: string;
        };
      };
      push_tokens: {
        Row: {
          id: string;
          user_id: string;
          token: string;
          platform: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          token: string;
          platform?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          token?: string;
          platform?: string | null;
          created_at?: string;
        };
      };
    };
    Functions: {
      increment_view_count: {
        Args: { read_id: string };
        Returns: void;
      };
    };
    Enums: {};
  };
}
